/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElM: typeof import('element-plus/es')['ElM']
  const ElMe: typeof import('element-plus/es')['ElMe']
  const ElMess: typeof import('element-plus/es')['ElMess']
  const ElMessa: typeof import('element-plus/es')['ElMessa']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
  const ElMme: typeof import('element-plus/es')['ElMme']
}
